apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sty292kfy-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sty292kfy-java-quarkus-gitops